<h1>Order palced successfully.....</h1>
<iframe id="inlineFrameExample"
    title="Inline Frame Example"
    width="500"
    height="500"
    src="https://alanstorm.com/magento_2_knockoutjs_integration/">
</iframe>
<div>
    <div data-bind="event: { mouseover: enableDetails, mouseout: disableDetails }">
        Mouse over me
    </div>
    <div data-bind="visible: detailsEnabled">
        Details
    </div>
</div>
 
<script type="text/javascript">
    var viewModel = {
        detailsEnabled: ko.observable(false),
        enableDetails: function() {
            this.detailsEnabled(true);
        },
        disableDetails: function() {
            this.detailsEnabled(false);
        }
    };
    ko.applyBindings(viewModel);
</script>