<?php
/**
 * @var \Magento\Customer\Api\Data\AttributeMetadataInterface $attribute
 */
$attribute = $block->getAttribute();
if($attribute):
?>
<div class="field <?= $attribute->getAttributeCode() ?> <?= $attribute->isRequired()?"required":"" ?>">
    <label for="<?= $attribute->getAttributeCode() ?>" class="label">
    <span>
        <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
    </span>
    </label>
    <div class="control">
            <input type="text"
                name="<?= $attribute->getAttributeCode() ?>"
                id="<?= $attribute->getAttributeCode() ?>"
                value="<?= $block->escapeHtmlAttr($block->getAttributeValue()) ?>"
                title="<?= $block->escapeHtmlAttr(__($attribute->getStoreLabel())) ?>"
                class="input-text <?= $attribute->getFrontendClass() ?>"
            />
            <?php /**
            if($attribute->getAttributeCode() == 'epayerz_wallet_id' && $block->getAttributeValue() == '' ){?>
                <p>To Create Epayerz wallet click on <a href="https://web.epayerz.com:83/Agent/SignUp" target="_blank">this link.</a></p>
            <?php } else {?>
                <p>To Login Epayerz Wallet click on <a href="https://web.epayerz.com:83" target="_blank">this link.</a></p>
            <?php }**/?>
    </div>
</div>
<?php
endif;
?>