<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<?php/* $gridrecords = $block->getdonorCollection(); */?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
            <th scope="col" class="col id"><?php echo __('Id') ?></th>
            <th scope="col" class="col name"><?php echo __('Item Name') ?></th>
            <th scope="col" class="col description"><?php echo __('Description') ?></th>
            <th scope="col" class="col donated-by"><?php echo __('Donated By') ?></th>
            <th scope="col" class="col donor-type"><?php echo __('Donor Type') ?></th>
            <th scope="col" class="col qnt-donated"><?php echo __('Qunatity Donated') ?></th>
            <th scope="col" class="col donation-date"><?php echo __('Donation Date') ?></th>

        </tr>
            </thead>
            <tbody>
            <?php
          //  foreach ($gridrecords as $donor): ?>
                <tr>
            <td data-th="<?= $block->escapeHtml(__('Id')) ?>" class="col id">
                <?php echo $donor['donor_id']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Item Name')) ?>" class="col name">
                <?php echo $donor['product_sku']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Description')) ?>" class="col description">
                <?php echo $donor['description']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Donated By')) ?>" class="col donated-by">
                <?php echo $donor['donated_by']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Donor Type')) ?>" class="col donor-type">
                <?php echo $donor['donor_type']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Qunatity Donated')) ?>" class="col qnt-donated">
                <?php echo $donor['qty']; ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Donation Date')) ?>" class="col donation-date">
                <?php echo $donor['created_at']; ?>
            </td>
        </tr>
            <?php/* endforeach;*/ ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
